### ISSUE TITLE
Cannot specify both default and name_property together

### ISSUE THREAD

**Issue by Poohblah** [atomic-penguin/cookbook-krb5#26]
When converging the `krb5::default` recipe, I get the following warning:

```
Deprecated features used!
         Cannot specify both default and name_property together on property path of resource krb5_keytab. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
           - /tmp/kitchen/cache/cookbooks/krb5/resources/keytab.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property principal of resource krb5_principal. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
           - /tmp/kitchen/cache/cookbooks/krb5/resources/principal.rb:23:in `class_from_file'
```

As this will soon be an error instead of a warning, it should be fixed.

(If I have the time, I'll try to look into this and submit a PR to fix it.)

**Comment by funjon** [comment]
+1. I've been told Chef-13 is coming Soon (tm), like before end of year.
